version: '3.8'

services:
  db:
    image: cockroachdb/cockroach:v21.1.16
    restart: always
    container_name: donna-md-service-db
    command: start-single-node --insecure
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - my_network

  app:
    container_name: donna-md-service
    build: .
    depends_on:
      - db
    ports:
      - 50051:50051
    volumes:
      - ./.env:/.env
    networks:
      - my_network
  
  air:
    image: cosmtrek/air
    container_name: donna-md-service-air
    working_dir: /app
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - my_network

networks:
  my_network: