version: '3.8'

services:
  db:
    image: cockroachdb/cockroach:v21.1.16
    restart: always
    container_name: donna-md-service-db
    command: start-single-node --insecure
    ports:
      - 26257:26257
      - 8080:8080

  migrate:
    image: migrate/migrate
    volumes:
      - ./database/migrations:/database/migrations
    depends_on:
      - db
    command: ["-path", "./database/migrations", "-database", "cockroachdb://root@db:26257/defaultdb?sslmode=disable", "up"]

  app:
    container_name: donna-md-service
    build: .
    depends_on:
      - migrate
    ports:
      - 50051:50051
    volumes:
      - ./.env:/.env
  
  air:
    image: cosmtrek/air
    container_name: donna-md-service-air
    working_dir: /app
    depends_on:
      - migrate
    volumes:
      - ./:/app