version: '3.8'

services:
  app:
    container_name: donna-md-service
    build: .
    ports:
      - 50051:50051
  
  air:
    image: cosmtrek/air
    container_name: donna-md-service-air
    working_dir: /app
    # ports:
      # - 50051:50051
    volumes:
      - ./:/app
